# -*- coding: utf-8 -*-
"""HolaMundo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGtGGXmQj_GP6VWz1a4v5gcJ5Py_yGJI
"""

pip install streamlit

import streamlit as st

st.write('Hello, *World!* : sunglasses:')